WIP: Windows build GitHub Action
crazywhalecc/static-php-cli pull request #420
Opened 2024-04-24 18:17 UTC by simonhamp

## What does this PR do?
Adds a GitHub Action for building on Windows.

This is a first pass that builds an executable, but it's still WIP - please leave this PR open as I will be pushing to the original branch as we work through fixing it.

Current known issues:
- [ ] It currently seems to only build PHP8.2 - I haven't started to dig into why
- [ ] #419 
- [ ] When you get past SmartScreen, you hit #418 

## Checklist before merging

> If your PR involves the changes mentioned below and completed the action, please tick the corresponding option.
> If a modification is not involved, please skip it directly.

- [ ] If it's a extension or dependency update, make sure adding related extensions in `src/global/test-extensions.php`.
- [ ] If you changed the behavior of static-php-cli, add docs in [static-php/static-php-cli-docs](https://github.com/static-php/static-php-cli-docs) .
- [ ] If you updated `config/xxxx.json` content, run `bin/spc dev:sort-config xxx`.

2024-05-03 00:37 UTC, simonhamp commented
The test failures here seem to be due to hitting GitHub's rate limits

2024-05-04 16:17 UTC, crazywhalecc commented
It seems that my GITHUB_TOKEN has expired, I will update it.

2024-05-06 02:34 UTC, crazywhalecc requested changes

2024-05-06 02:34 UTC, crazywhalecc commented on .github/workflows/build-windows-x86_64.yml
> +        description: build fpm binary
Windows doesn't support fpm sapi.

2024-05-06 03:58 UTC, crazywhalecc approved these changes

2024-05-06 03:59 UTC, merged